version: "3.7"
networks:
  webnet:
    driver: overlay

volumes:
  mysql_db:

services:
  db:
    image: florinrm/proiect_idp:db
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: 1234

  client:
    image: florinrm/proiect_idp:client
    stdin_open: true
    tty: true
    ports:
      - "8888:5000"
    depends_on:
      - db
    networks:
      - webnet

  app:
    image: florinrm/proiect_idp:app
    depends_on:
      - db
    ports:
      - "5001:5001"
    networks:
      - webnet

  admin:
    image: florinrm/proiect_idp:admin
    depends_on:
      - db
    stdin_open: true
    ports:
      - "5002:5002"
    tty: true
    networks:
      - webnet