 
version: '3.3'

services:
    mysql:
        image: mysql
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mysql
            MYSQL_USER: server
            MYSQL_PASSWORD: server
       
    admin:
        image: florinrm/proiect_idp:admin
        restart: always
        tty: true
        stdin_open: true
        ports:
            - 5001:5001

    server:
        image: florinrm/proiect_idp:server
        restart: always
        links:
            - "mysql:database"
        ports:
            - 5000:5000

    client:
        image: florinrm/proiect_idp:client
        ports:
            - 5002:5002

    grafana:
        image: grafana/grafana:5.1.0
        ports:
            - 3000:3000
        user: "69"

volumes:
    mysql_data: {}